# Generated by Django 2.1.8 on 2019-04-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='novel',
            name='type',
            field=models.ForeignKey(help_text='类型', on_delete=django.db.models.deletion.CASCADE, to='novels.Type', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(help_text='作品', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.Novel', verbose_name='作品'),
        ),
    ]
