# Generated by Django 2.2 on 2019-04-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20190401_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.URLField(blank=True, default='qiniu.tuscanyyy.top/cover', help_text='封面', null=True, verbose_name='封面'),
        ),
    ]
