# Generated by Django 2.2 on 2019-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20190417_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.URLField(blank=True, default='qiniu.tuscanyyy.top/cover.jpg', help_text='封面', null=True, verbose_name='封面'),
        ),
    ]
