# Generated by Django 2.2 on 2019-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20190422_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签', max_length=8, verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.RenameField(
            model_name='novel',
            old_name='last_update_time',
            new_name='update_time',
        ),
        migrations.AddField(
            model_name='type',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='标签', to='novels.Tag', verbose_name='标签'),
        ),
    ]
