# Generated by Django 2.2 on 2019-04-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_auto_20190425_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='type',
            name='create_time',
        ),
    ]
