# Generated by Django 2.2 on 2019-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_auto_20190425_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='标签', max_length=100, verbose_name='标签'),
        ),
    ]
