# Generated by Django 2.1.8 on 2019-04-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, help_text='性别', max_length=15, verbose_name='性别'),
        ),
    ]
