# Generated by Django 2.2 on 2019-04-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190402_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, default='qiniu.tuscanyyy.top/avatar', help_text='头像', null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, help_text='性别: 0(男), 1(女), 2(保密)', verbose_name='性别'),
        ),
    ]
