# Generated by Django 2.2 on 2019-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190417_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, default='qiniu.tuscanyyy.top/avatar.jpg', help_text='头像', null=True, verbose_name='头像'),
        ),
    ]
