# Generated by Django 2.2 on 2019-04-25 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190422_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(blank=True, help_text='关注', related_name='_userprofile_follow_+', to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
    ]
