# Generated by Django 2.2 on 2019-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow_num',
            field=models.PositiveIntegerField(default=0, help_text='关注人数', verbose_name='关注人数'),
        ),
    ]
