# Generated by Django 2.2 on 2019-04-18 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20190417_0100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20190401_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='novel',
            field=models.ForeignKey(help_text='作品', on_delete=django.db.models.deletion.CASCADE, to='novels.Novel', verbose_name='作品'),
        ),
        migrations.AlterField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='like',
            name='novel',
            field=models.ForeignKey(help_text='作品', on_delete=django.db.models.deletion.CASCADE, to='novels.Novel', verbose_name='作品'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Cmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='内容', max_length=500, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('novel', models.ForeignKey(help_text='作品', on_delete=django.db.models.deletion.CASCADE, to='novels.Novel', verbose_name='作品')),
                ('parent', models.ForeignKey(help_text='上级评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_cmt', to='operation.Cmt', verbose_name='上级评论')),
                ('reply', models.ForeignKey(help_text='回复', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to=settings.AUTH_USER_MODEL, verbose_name='回复')),
                ('root', models.ForeignKey(help_text='根评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_cmt', to='operation.Cmt', verbose_name='根评论')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-create_time'],
            },
        ),
    ]
