# Generated by Django 2.2 on 2019-04-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20190418_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmt',
            name='parent',
        ),
        migrations.AlterField(
            model_name='cmt',
            name='root',
            field=models.ForeignKey(help_text='评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_cmt', to='operation.Cmt', verbose_name='评论'),
        ),
    ]
