# Generated by Django 2.2 on 2019-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
