# Generated by Django 2.2 on 2019-04-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_history_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-update_time'], 'verbose_name': '历史记录', 'verbose_name_plural': '历史记录'},
        ),
    ]
