# Generated by Django 2.2 on 2019-04-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_searchrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrecord',
            name='novel',
        ),
        migrations.AddField(
            model_name='searchrecord',
            name='content',
            field=models.CharField(help_text='内容', max_length=100, null=True, verbose_name='内容'),
        ),
    ]
